### ISSUE TITLE
Недоработки сайта

### ISSUE THREAD

**Issue by mglknFSD** [DGRTF/FSD#17]
1. Баг с dropdown 

![dropdown](https://user-images.githubusercontent.com/75975369/107114779-a3995a80-6879-11eb-8a3b-cf3391b5a083.png)

**Comment by mglknFSD** [comment]
2. expandable checkbox. Логичное поведение для подобного компонента отодвигать нижний элемент при появлении.
![expandable checkbox](https://user-images.githubusercontent.com/75975369/107114863-1efb0c00-687a-11eb-8ada-0daa35f9371f.png)

**Comment by mglknFSD** [comment]
3. У всех элементов форм должны быть активные лейблы. Т е при клике на них должен срабатывать чекбокс, радиокнопка, происходить фокус и тому подобное.

https://user-images.githubusercontent.com/75975369/107114925-6da8a600-687a-11eb-87ce-5328551a3ce3.mp4

**Comment by mglknFSD** [comment]
4. Для кнопок не работает hover эффект описаный в макете

https://user-images.githubusercontent.com/75975369/107115088-3a1a4b80-687b-11eb-956a-d88fac649a41.mp4

**Comment by mglknFSD** [comment]
5. Ошибки при загрузке страниц
![errors](https://user-images.githubusercontent.com/75975369/107115154-b01eb280-687b-11eb-93ae-030524f39c64.png)
![errors2](https://user-images.githubusercontent.com/75975369/107115156-b319a300-687b-11eb-8b16-59f921e90197.png)

**Comment by DGRTF** [comment]
> 1. expandable checkbox. Логичное поведение для подобного компонента отодвигать нижний элемент при появлении.
>    ![expandable checkbox](https://user-images.githubusercontent.com/75975369/107114863-1efb0c00-687a-11eb-8ada-0daa35f9371f.png)

https://dgrtf.github.io/FSD/search.html

**Comment by DGRTF** [comment]
> 1. Для кнопок не работает hover эффект описаный в макете
> 
>  2021-02-06-12-59-08.mp4

Насколько я понял это не эффект наведения и фокуса ,а свойство disable кнопки. и они действительно имеют такие стили на [disable]
